// source: GroupRoom/GroupRoomSearch.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var GroupRoom_GroupRoomTeamInfo_pb = require('../GroupRoom/GroupRoomTeamInfo_pb.js');
goog.object.extend(proto, GroupRoom_GroupRoomTeamInfo_pb);
goog.exportSymbol('proto.PbModel.GroupRoom.GroupRoomSearchReq', null, global);
goog.exportSymbol('proto.PbModel.GroupRoom.GroupRoomSearchRes', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.GroupRoom.GroupRoomSearchReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GroupRoom.GroupRoomSearchReq.displayName = 'proto.PbModel.GroupRoom.GroupRoomSearchReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.GroupRoom.GroupRoomSearchRes.repeatedFields_, null);
};
goog.inherits(proto.PbModel.GroupRoom.GroupRoomSearchRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GroupRoom.GroupRoomSearchRes.displayName = 'proto.PbModel.GroupRoom.GroupRoomSearchRes';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GroupRoom.GroupRoomSearchReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GroupRoom.GroupRoomSearchReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    teamtype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    subtype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    playerid: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchReq}
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GroupRoom.GroupRoomSearchReq;
  return proto.PbModel.GroupRoom.GroupRoomSearchReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GroupRoom.GroupRoomSearchReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchReq}
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTeamtype(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSubtype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GroupRoom.GroupRoomSearchReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GroupRoom.GroupRoomSearchReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeamtype();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSubtype();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPlayerid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int32 TeamType = 1;
 * @return {number}
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.prototype.getTeamtype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchReq} returns this
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.prototype.setTeamtype = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 SubType = 2;
 * @return {number}
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.prototype.getSubtype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchReq} returns this
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.prototype.setSubtype = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string PlayerId = 3;
 * @return {string}
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.prototype.getPlayerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchReq} returns this
 */
proto.PbModel.GroupRoom.GroupRoomSearchReq.prototype.setPlayerid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GroupRoom.GroupRoomSearchRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GroupRoom.GroupRoomSearchRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    listList: jspb.Message.toObjectList(msg.getListList(),
    GroupRoom_GroupRoomTeamInfo_pb.GroupRoomTeamInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchRes}
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GroupRoom.GroupRoomSearchRes;
  return proto.PbModel.GroupRoom.GroupRoomSearchRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GroupRoom.GroupRoomSearchRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchRes}
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GroupRoom_GroupRoomTeamInfo_pb.GroupRoomTeamInfo;
      reader.readMessage(value,GroupRoom_GroupRoomTeamInfo_pb.GroupRoomTeamInfo.deserializeBinaryFromReader);
      msg.addList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GroupRoom.GroupRoomSearchRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GroupRoom.GroupRoomSearchRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      GroupRoom_GroupRoomTeamInfo_pb.GroupRoomTeamInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated GroupRoomTeamInfo List = 1;
 * @return {!Array<!proto.PbModel.GroupRoom.GroupRoomTeamInfo>}
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.prototype.getListList = function() {
  return /** @type{!Array<!proto.PbModel.GroupRoom.GroupRoomTeamInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, GroupRoom_GroupRoomTeamInfo_pb.GroupRoomTeamInfo, 1));
};


/**
 * @param {!Array<!proto.PbModel.GroupRoom.GroupRoomTeamInfo>} value
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchRes} returns this
*/
proto.PbModel.GroupRoom.GroupRoomSearchRes.prototype.setListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.PbModel.GroupRoom.GroupRoomTeamInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.GroupRoom.GroupRoomTeamInfo}
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.prototype.addList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.PbModel.GroupRoom.GroupRoomTeamInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.GroupRoom.GroupRoomSearchRes} returns this
 */
proto.PbModel.GroupRoom.GroupRoomSearchRes.prototype.clearListList = function() {
  return this.setListList([]);
};


goog.object.extend(exports, proto.PbModel.GroupRoom);
