// source: GVGServer/GVGServerMapClientAttackReq.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var GVGServer_GVGServerPbPoint_pb = require('../GVGServer/GVGServerPbPoint_pb.js');
goog.object.extend(proto, GVGServer_GVGServerPbPoint_pb);
var Common_ResultStatus_pb = require('../Common/ResultStatus_pb.js');
goog.object.extend(proto, Common_ResultStatus_pb);
goog.exportSymbol('proto.PbModel.GvGServer.BatchAttackTeamInfo', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.GiveUpLandReq', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.GiveUpLandRes', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.MapClientAttackReq', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.MapClientAttackRes', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.MapClientBatchAttackReq', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.MapClientBatchAttackRes', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.TeamType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.MapClientAttackReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.GvGServer.MapClientAttackReq.repeatedFields_, null);
};
goog.inherits(proto.PbModel.GvGServer.MapClientAttackReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.MapClientAttackReq.displayName = 'proto.PbModel.GvGServer.MapClientAttackReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.MapClientAttackRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.GvGServer.MapClientAttackRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.MapClientAttackRes.displayName = 'proto.PbModel.GvGServer.MapClientAttackRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.GiveUpLandReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.GvGServer.GiveUpLandReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.GiveUpLandReq.displayName = 'proto.PbModel.GvGServer.GiveUpLandReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.GiveUpLandRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.GvGServer.GiveUpLandRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.GiveUpLandRes.displayName = 'proto.PbModel.GvGServer.GiveUpLandRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.GvGServer.MapClientBatchAttackReq.repeatedFields_, null);
};
goog.inherits(proto.PbModel.GvGServer.MapClientBatchAttackReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.MapClientBatchAttackReq.displayName = 'proto.PbModel.GvGServer.MapClientBatchAttackReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.GvGServer.MapClientBatchAttackRes.repeatedFields_, null);
};
goog.inherits(proto.PbModel.GvGServer.MapClientBatchAttackRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.MapClientBatchAttackRes.displayName = 'proto.PbModel.GvGServer.MapClientBatchAttackRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.GvGServer.BatchAttackTeamInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.BatchAttackTeamInfo.displayName = 'proto.PbModel.GvGServer.BatchAttackTeamInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.GvGServer.MapClientAttackReq.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.MapClientAttackReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.MapClientAttackReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapClientAttackReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    guildid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    teamtype: jspb.Message.getFieldWithDefault(msg, 4, 0),
    teamid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    routespointsList: jspb.Message.toObjectList(msg.getRoutespointsList(),
    GVGServer_GVGServerPbPoint_pb.PbPoint.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.MapClientAttackReq}
 */
proto.PbModel.GvGServer.MapClientAttackReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.MapClientAttackReq;
  return proto.PbModel.GvGServer.MapClientAttackReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.MapClientAttackReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.MapClientAttackReq}
 */
proto.PbModel.GvGServer.MapClientAttackReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuildid(value);
      break;
    case 4:
      var value = /** @type {!proto.PbModel.GvGServer.TeamType} */ (reader.readEnum());
      msg.setTeamtype(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTeamid(value);
      break;
    case 6:
      var value = new GVGServer_GVGServerPbPoint_pb.PbPoint;
      reader.readMessage(value,GVGServer_GVGServerPbPoint_pb.PbPoint.deserializeBinaryFromReader);
      msg.addRoutespoints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.MapClientAttackReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.MapClientAttackReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapClientAttackReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGuildid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTeamtype();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTeamid();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getRoutespointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      GVGServer_GVGServerPbPoint_pb.PbPoint.serializeBinaryToWriter
    );
  }
};


/**
 * optional string PlayerId = 1;
 * @return {string}
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.getPlayerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapClientAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.setPlayerid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string GuildId = 3;
 * @return {string}
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.getGuildid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapClientAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.setGuildid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional TeamType TeamType = 4;
 * @return {!proto.PbModel.GvGServer.TeamType}
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.getTeamtype = function() {
  return /** @type {!proto.PbModel.GvGServer.TeamType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.PbModel.GvGServer.TeamType} value
 * @return {!proto.PbModel.GvGServer.MapClientAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.setTeamtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional int32 TeamId = 5;
 * @return {number}
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.getTeamid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.MapClientAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.setTeamid = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated PbPoint RoutesPoints = 6;
 * @return {!Array<!proto.PbModel.GvGServer.PbPoint>}
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.getRoutespointsList = function() {
  return /** @type{!Array<!proto.PbModel.GvGServer.PbPoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, GVGServer_GVGServerPbPoint_pb.PbPoint, 6));
};


/**
 * @param {!Array<!proto.PbModel.GvGServer.PbPoint>} value
 * @return {!proto.PbModel.GvGServer.MapClientAttackReq} returns this
*/
proto.PbModel.GvGServer.MapClientAttackReq.prototype.setRoutespointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.PbModel.GvGServer.PbPoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.GvGServer.PbPoint}
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.addRoutespoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.PbModel.GvGServer.PbPoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.GvGServer.MapClientAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientAttackReq.prototype.clearRoutespointsList = function() {
  return this.setRoutespointsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.MapClientAttackRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.MapClientAttackRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.MapClientAttackRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapClientAttackRes.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.MapClientAttackRes}
 */
proto.PbModel.GvGServer.MapClientAttackRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.MapClientAttackRes;
  return proto.PbModel.GvGServer.MapClientAttackRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.MapClientAttackRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.MapClientAttackRes}
 */
proto.PbModel.GvGServer.MapClientAttackRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.MapClientAttackRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.MapClientAttackRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.MapClientAttackRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapClientAttackRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.GiveUpLandReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.GiveUpLandReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.GiveUpLandReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    guildid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    point: (f = msg.getPoint()) && GVGServer_GVGServerPbPoint_pb.PbPoint.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.GiveUpLandReq}
 */
proto.PbModel.GvGServer.GiveUpLandReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.GiveUpLandReq;
  return proto.PbModel.GvGServer.GiveUpLandReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.GiveUpLandReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.GiveUpLandReq}
 */
proto.PbModel.GvGServer.GiveUpLandReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuildid(value);
      break;
    case 3:
      var value = new GVGServer_GVGServerPbPoint_pb.PbPoint;
      reader.readMessage(value,GVGServer_GVGServerPbPoint_pb.PbPoint.deserializeBinaryFromReader);
      msg.setPoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.GiveUpLandReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.GiveUpLandReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.GiveUpLandReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGuildid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPoint();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      GVGServer_GVGServerPbPoint_pb.PbPoint.serializeBinaryToWriter
    );
  }
};


/**
 * optional string PlayerId = 1;
 * @return {string}
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.getPlayerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.GiveUpLandReq} returns this
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.setPlayerid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string GuildId = 2;
 * @return {string}
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.getGuildid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.GiveUpLandReq} returns this
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.setGuildid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional PbPoint Point = 3;
 * @return {?proto.PbModel.GvGServer.PbPoint}
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.getPoint = function() {
  return /** @type{?proto.PbModel.GvGServer.PbPoint} */ (
    jspb.Message.getWrapperField(this, GVGServer_GVGServerPbPoint_pb.PbPoint, 3));
};


/**
 * @param {?proto.PbModel.GvGServer.PbPoint|undefined} value
 * @return {!proto.PbModel.GvGServer.GiveUpLandReq} returns this
*/
proto.PbModel.GvGServer.GiveUpLandReq.prototype.setPoint = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.GvGServer.GiveUpLandReq} returns this
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.clearPoint = function() {
  return this.setPoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.GvGServer.GiveUpLandReq.prototype.hasPoint = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.GiveUpLandRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.GiveUpLandRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.GiveUpLandRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.GiveUpLandRes.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.GiveUpLandRes}
 */
proto.PbModel.GvGServer.GiveUpLandRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.GiveUpLandRes;
  return proto.PbModel.GvGServer.GiveUpLandRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.GiveUpLandRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.GiveUpLandRes}
 */
proto.PbModel.GvGServer.GiveUpLandRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.GiveUpLandRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.GiveUpLandRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.GiveUpLandRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.GiveUpLandRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.MapClientBatchAttackReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.MapClientBatchAttackReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    guildid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    teamtype: jspb.Message.getFieldWithDefault(msg, 3, 0),
    teamidList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    routespointsList: jspb.Message.toObjectList(msg.getRoutespointsList(),
    GVGServer_GVGServerPbPoint_pb.PbPoint.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.MapClientBatchAttackReq;
  return proto.PbModel.GvGServer.MapClientBatchAttackReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.MapClientBatchAttackReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuildid(value);
      break;
    case 3:
      var value = /** @type {!proto.PbModel.GvGServer.TeamType} */ (reader.readEnum());
      msg.setTeamtype(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setTeamidList(value);
      break;
    case 5:
      var value = new GVGServer_GVGServerPbPoint_pb.PbPoint;
      reader.readMessage(value,GVGServer_GVGServerPbPoint_pb.PbPoint.deserializeBinaryFromReader);
      msg.addRoutespoints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.MapClientBatchAttackReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.MapClientBatchAttackReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGuildid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTeamtype();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getTeamidList();
  if (f.length > 0) {
    writer.writePackedInt32(
      4,
      f
    );
  }
  f = message.getRoutespointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      GVGServer_GVGServerPbPoint_pb.PbPoint.serializeBinaryToWriter
    );
  }
};


/**
 * optional string PlayerId = 1;
 * @return {string}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.getPlayerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.setPlayerid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string GuildId = 2;
 * @return {string}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.getGuildid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.setGuildid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional TeamType TeamType = 3;
 * @return {!proto.PbModel.GvGServer.TeamType}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.getTeamtype = function() {
  return /** @type {!proto.PbModel.GvGServer.TeamType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.PbModel.GvGServer.TeamType} value
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.setTeamtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * repeated int32 TeamId = 4;
 * @return {!Array<number>}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.getTeamidList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.setTeamidList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.addTeamid = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.clearTeamidList = function() {
  return this.setTeamidList([]);
};


/**
 * repeated PbPoint RoutesPoints = 5;
 * @return {!Array<!proto.PbModel.GvGServer.PbPoint>}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.getRoutespointsList = function() {
  return /** @type{!Array<!proto.PbModel.GvGServer.PbPoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, GVGServer_GVGServerPbPoint_pb.PbPoint, 5));
};


/**
 * @param {!Array<!proto.PbModel.GvGServer.PbPoint>} value
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq} returns this
*/
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.setRoutespointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.PbModel.GvGServer.PbPoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.GvGServer.PbPoint}
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.addRoutespoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.PbModel.GvGServer.PbPoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackReq} returns this
 */
proto.PbModel.GvGServer.MapClientBatchAttackReq.prototype.clearRoutespointsList = function() {
  return this.setRoutespointsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.MapClientBatchAttackRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.MapClientBatchAttackRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    resinfoList: jspb.Message.toObjectList(msg.getResinfoList(),
    proto.PbModel.GvGServer.BatchAttackTeamInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackRes}
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.MapClientBatchAttackRes;
  return proto.PbModel.GvGServer.MapClientBatchAttackRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.MapClientBatchAttackRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackRes}
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.PbModel.GvGServer.BatchAttackTeamInfo;
      reader.readMessage(value,proto.PbModel.GvGServer.BatchAttackTeamInfo.deserializeBinaryFromReader);
      msg.addResinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.MapClientBatchAttackRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.MapClientBatchAttackRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResinfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.PbModel.GvGServer.BatchAttackTeamInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BatchAttackTeamInfo ResInfo = 1;
 * @return {!Array<!proto.PbModel.GvGServer.BatchAttackTeamInfo>}
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.prototype.getResinfoList = function() {
  return /** @type{!Array<!proto.PbModel.GvGServer.BatchAttackTeamInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.GvGServer.BatchAttackTeamInfo, 1));
};


/**
 * @param {!Array<!proto.PbModel.GvGServer.BatchAttackTeamInfo>} value
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackRes} returns this
*/
proto.PbModel.GvGServer.MapClientBatchAttackRes.prototype.setResinfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.PbModel.GvGServer.BatchAttackTeamInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.GvGServer.BatchAttackTeamInfo}
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.prototype.addResinfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.PbModel.GvGServer.BatchAttackTeamInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.GvGServer.MapClientBatchAttackRes} returns this
 */
proto.PbModel.GvGServer.MapClientBatchAttackRes.prototype.clearResinfoList = function() {
  return this.setResinfoList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.BatchAttackTeamInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.BatchAttackTeamInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    teamid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    status: jspb.Message.getFieldWithDefault(msg, 2, 0),
    errormsg: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.BatchAttackTeamInfo}
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.BatchAttackTeamInfo;
  return proto.PbModel.GvGServer.BatchAttackTeamInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.BatchAttackTeamInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.BatchAttackTeamInfo}
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTeamid(value);
      break;
    case 2:
      var value = /** @type {!proto.PbModel.Common.ResultStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.BatchAttackTeamInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.BatchAttackTeamInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeamid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getErrormsg();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int32 TeamId = 1;
 * @return {number}
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.prototype.getTeamid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.BatchAttackTeamInfo} returns this
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.prototype.setTeamid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional PbModel.Common.ResultStatus Status = 2;
 * @return {!proto.PbModel.Common.ResultStatus}
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.prototype.getStatus = function() {
  return /** @type {!proto.PbModel.Common.ResultStatus} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.PbModel.Common.ResultStatus} value
 * @return {!proto.PbModel.GvGServer.BatchAttackTeamInfo} returns this
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string ErrorMsg = 3;
 * @return {string}
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.prototype.getErrormsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.BatchAttackTeamInfo} returns this
 */
proto.PbModel.GvGServer.BatchAttackTeamInfo.prototype.setErrormsg = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.PbModel.GvGServer.TeamType = {
  SELF: 0,
  MIXED: 1
};

goog.object.extend(exports, proto.PbModel.GvGServer);
