// source: GVGServer/GVGServerMapPointDetialInfo.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var GVGServer_GVGServerPbPoint_pb = require('../GVGServer/GVGServerPbPoint_pb.js');
goog.object.extend(proto, GVGServer_GVGServerPbPoint_pb);
var GVGServer_GVGServerMapPointInfo_pb = require('../GVGServer/GVGServerMapPointInfo_pb.js');
goog.object.extend(proto, GVGServer_GVGServerMapPointInfo_pb);
goog.exportSymbol('proto.PbModel.GvGServer.DefMapPointTeamInfo', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.MapPointDetailInfo', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.MapPointDetailInfo.ExinfooneofCase', null, global);
goog.exportSymbol('proto.PbModel.GvGServer.MapPointTeamInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.MapPointDetailInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.GvGServer.MapPointDetailInfo.repeatedFields_, proto.PbModel.GvGServer.MapPointDetailInfo.oneofGroups_);
};
goog.inherits(proto.PbModel.GvGServer.MapPointDetailInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.MapPointDetailInfo.displayName = 'proto.PbModel.GvGServer.MapPointDetailInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.GvGServer.DefMapPointTeamInfo.repeatedFields_, null);
};
goog.inherits(proto.PbModel.GvGServer.DefMapPointTeamInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.DefMapPointTeamInfo.displayName = 'proto.PbModel.GvGServer.DefMapPointTeamInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.GvGServer.MapPointTeamInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.GvGServer.MapPointTeamInfo.repeatedFields_, null);
};
goog.inherits(proto.PbModel.GvGServer.MapPointTeamInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.GvGServer.MapPointTeamInfo.displayName = 'proto.PbModel.GvGServer.MapPointTeamInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.GvGServer.MapPointDetailInfo.repeatedFields_ = [5];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.PbModel.GvGServer.MapPointDetailInfo.oneofGroups_ = [[50]];

/**
 * @enum {number}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.ExinfooneofCase = {
  EXINFOONEOF_NOT_SET: 0,
  DOORINFO: 50
};

/**
 * @return {proto.PbModel.GvGServer.MapPointDetailInfo.ExinfooneofCase}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getExinfooneofCase = function() {
  return /** @type {proto.PbModel.GvGServer.MapPointDetailInfo.ExinfooneofCase} */(jspb.Message.computeOneofCase(this, proto.PbModel.GvGServer.MapPointDetailInfo.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.MapPointDetailInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.MapPointDetailInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapPointDetailInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    point: (f = msg.getPoint()) && GVGServer_GVGServerPbPoint_pb.PbPoint.toObject(includeInstance, f),
    pointtype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    entityid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    defques: (f = msg.getDefques()) && proto.PbModel.GvGServer.DefMapPointTeamInfo.toObject(includeInstance, f),
    atklistList: jspb.Message.toObjectList(msg.getAtklistList(),
    proto.PbModel.GvGServer.MapPointTeamInfo.toObject, includeInstance),
    partsid: jspb.Message.getFieldWithDefault(msg, 6, 0),
    showtype: jspb.Message.getFieldWithDefault(msg, 7, 0),
    ownerid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    doorinfo: (f = msg.getDoorinfo()) && GVGServer_GVGServerMapPointInfo_pb.DoorInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.MapPointDetailInfo;
  return proto.PbModel.GvGServer.MapPointDetailInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.MapPointDetailInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GVGServer_GVGServerPbPoint_pb.PbPoint;
      reader.readMessage(value,GVGServer_GVGServerPbPoint_pb.PbPoint.deserializeBinaryFromReader);
      msg.setPoint(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPointtype(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntityid(value);
      break;
    case 4:
      var value = new proto.PbModel.GvGServer.DefMapPointTeamInfo;
      reader.readMessage(value,proto.PbModel.GvGServer.DefMapPointTeamInfo.deserializeBinaryFromReader);
      msg.setDefques(value);
      break;
    case 5:
      var value = new proto.PbModel.GvGServer.MapPointTeamInfo;
      reader.readMessage(value,proto.PbModel.GvGServer.MapPointTeamInfo.deserializeBinaryFromReader);
      msg.addAtklist(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPartsid(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setShowtype(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnerid(value);
      break;
    case 50:
      var value = new GVGServer_GVGServerMapPointInfo_pb.DoorInfo;
      reader.readMessage(value,GVGServer_GVGServerMapPointInfo_pb.DoorInfo.deserializeBinaryFromReader);
      msg.setDoorinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.MapPointDetailInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.MapPointDetailInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapPointDetailInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPoint();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      GVGServer_GVGServerPbPoint_pb.PbPoint.serializeBinaryToWriter
    );
  }
  f = message.getPointtype();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getEntityid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDefques();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.PbModel.GvGServer.DefMapPointTeamInfo.serializeBinaryToWriter
    );
  }
  f = message.getAtklistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.PbModel.GvGServer.MapPointTeamInfo.serializeBinaryToWriter
    );
  }
  f = message.getPartsid();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getShowtype();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getOwnerid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDoorinfo();
  if (f != null) {
    writer.writeMessage(
      50,
      f,
      GVGServer_GVGServerMapPointInfo_pb.DoorInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional PbPoint Point = 1;
 * @return {?proto.PbModel.GvGServer.PbPoint}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getPoint = function() {
  return /** @type{?proto.PbModel.GvGServer.PbPoint} */ (
    jspb.Message.getWrapperField(this, GVGServer_GVGServerPbPoint_pb.PbPoint, 1));
};


/**
 * @param {?proto.PbModel.GvGServer.PbPoint|undefined} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
*/
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setPoint = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.clearPoint = function() {
  return this.setPoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.hasPoint = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 PointType = 2;
 * @return {number}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getPointtype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setPointtype = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string EntityID = 3;
 * @return {string}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getEntityid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setEntityid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional DefMapPointTeamInfo DefQues = 4;
 * @return {?proto.PbModel.GvGServer.DefMapPointTeamInfo}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getDefques = function() {
  return /** @type{?proto.PbModel.GvGServer.DefMapPointTeamInfo} */ (
    jspb.Message.getWrapperField(this, proto.PbModel.GvGServer.DefMapPointTeamInfo, 4));
};


/**
 * @param {?proto.PbModel.GvGServer.DefMapPointTeamInfo|undefined} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
*/
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setDefques = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.clearDefques = function() {
  return this.setDefques(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.hasDefques = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated MapPointTeamInfo AtkList = 5;
 * @return {!Array<!proto.PbModel.GvGServer.MapPointTeamInfo>}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getAtklistList = function() {
  return /** @type{!Array<!proto.PbModel.GvGServer.MapPointTeamInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.GvGServer.MapPointTeamInfo, 5));
};


/**
 * @param {!Array<!proto.PbModel.GvGServer.MapPointTeamInfo>} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
*/
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setAtklistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.PbModel.GvGServer.MapPointTeamInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.addAtklist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.PbModel.GvGServer.MapPointTeamInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.clearAtklistList = function() {
  return this.setAtklistList([]);
};


/**
 * optional int32 PartsID = 6;
 * @return {number}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getPartsid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setPartsid = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 ShowType = 7;
 * @return {number}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getShowtype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setShowtype = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string OwnerId = 8;
 * @return {string}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getOwnerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setOwnerid = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional DoorInfo DoorInfo = 50;
 * @return {?proto.PbModel.GvGServer.DoorInfo}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.getDoorinfo = function() {
  return /** @type{?proto.PbModel.GvGServer.DoorInfo} */ (
    jspb.Message.getWrapperField(this, GVGServer_GVGServerMapPointInfo_pb.DoorInfo, 50));
};


/**
 * @param {?proto.PbModel.GvGServer.DoorInfo|undefined} value
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
*/
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.setDoorinfo = function(value) {
  return jspb.Message.setOneofWrapperField(this, 50, proto.PbModel.GvGServer.MapPointDetailInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.GvGServer.MapPointDetailInfo} returns this
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.clearDoorinfo = function() {
  return this.setDoorinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.GvGServer.MapPointDetailInfo.prototype.hasDoorinfo = function() {
  return jspb.Message.getField(this, 50) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.DefMapPointTeamInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.DefMapPointTeamInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    npcnum: jspb.Message.getFieldWithDefault(msg, 1, 0),
    npcid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    npcteamstr: jspb.Message.getFieldWithDefault(msg, 3, ""),
    deflistList: jspb.Message.toObjectList(msg.getDeflistList(),
    proto.PbModel.GvGServer.MapPointTeamInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.DefMapPointTeamInfo}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.DefMapPointTeamInfo;
  return proto.PbModel.GvGServer.DefMapPointTeamInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.DefMapPointTeamInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.DefMapPointTeamInfo}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNpcnum(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNpcid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNpcteamstr(value);
      break;
    case 4:
      var value = new proto.PbModel.GvGServer.MapPointTeamInfo;
      reader.readMessage(value,proto.PbModel.GvGServer.MapPointTeamInfo.deserializeBinaryFromReader);
      msg.addDeflist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.DefMapPointTeamInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.DefMapPointTeamInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNpcnum();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNpcid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getNpcteamstr();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDeflistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.PbModel.GvGServer.MapPointTeamInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 NpcNum = 1;
 * @return {number}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.getNpcnum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.DefMapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.setNpcnum = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 NpcId = 2;
 * @return {number}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.getNpcid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.DefMapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.setNpcid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string NpcTeamStr = 3;
 * @return {string}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.getNpcteamstr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.DefMapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.setNpcteamstr = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated MapPointTeamInfo DefList = 4;
 * @return {!Array<!proto.PbModel.GvGServer.MapPointTeamInfo>}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.getDeflistList = function() {
  return /** @type{!Array<!proto.PbModel.GvGServer.MapPointTeamInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.GvGServer.MapPointTeamInfo, 4));
};


/**
 * @param {!Array<!proto.PbModel.GvGServer.MapPointTeamInfo>} value
 * @return {!proto.PbModel.GvGServer.DefMapPointTeamInfo} returns this
*/
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.setDeflistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.PbModel.GvGServer.MapPointTeamInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo}
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.addDeflist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.PbModel.GvGServer.MapPointTeamInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.GvGServer.DefMapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.DefMapPointTeamInfo.prototype.clearDeflistList = function() {
  return this.setDeflistList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.GvGServer.MapPointTeamInfo.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.GvGServer.MapPointTeamInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.GvGServer.MapPointTeamInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapPointTeamInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    guildid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    guildname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    isnpc: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    npcid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    ismixteam: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    teamstr: jspb.Message.getFieldWithDefault(msg, 7, ""),
    playername: jspb.Message.getFieldWithDefault(msg, 8, ""),
    effectlistList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    weaknum: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.GvGServer.MapPointTeamInfo;
  return proto.PbModel.GvGServer.MapPointTeamInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.GvGServer.MapPointTeamInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuildid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuildname(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsnpc(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNpcid(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsmixteam(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeamstr(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayername(value);
      break;
    case 9:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setEffectlistList(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWeaknum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.GvGServer.MapPointTeamInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.GvGServer.MapPointTeamInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.GvGServer.MapPointTeamInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGuildid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGuildname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIsnpc();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getNpcid();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getIsmixteam();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getTeamstr();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPlayername();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getEffectlistList();
  if (f.length > 0) {
    writer.writePackedInt32(
      9,
      f
    );
  }
  f = message.getWeaknum();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
};


/**
 * optional string PlayerId = 1;
 * @return {string}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getPlayerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setPlayerid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string GuildId = 2;
 * @return {string}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getGuildid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setGuildid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string GuildName = 3;
 * @return {string}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getGuildname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setGuildname = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool IsNpc = 4;
 * @return {boolean}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getIsnpc = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setIsnpc = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int32 NpcId = 5;
 * @return {number}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getNpcid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setNpcid = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool isMixTeam = 6;
 * @return {boolean}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getIsmixteam = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setIsmixteam = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string TeamStr = 7;
 * @return {string}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getTeamstr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setTeamstr = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string playerName = 8;
 * @return {string}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getPlayername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setPlayername = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * repeated int32 EffectList = 9;
 * @return {!Array<number>}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getEffectlistList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setEffectlistList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.addEffectlist = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.clearEffectlistList = function() {
  return this.setEffectlistList([]);
};


/**
 * optional int32 WeakNum = 10;
 * @return {number}
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.getWeaknum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.GvGServer.MapPointTeamInfo} returns this
 */
proto.PbModel.GvGServer.MapPointTeamInfo.prototype.setWeaknum = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


goog.object.extend(exports, proto.PbModel.GvGServer);
