// source: Team/TeamModel.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.PbModel.Team.ModuleTeamInfo', null, global);
goog.exportSymbol('proto.PbModel.Team.Team', null, global);
goog.exportSymbol('proto.PbModel.Team.TeamHeroDetailInfoItem', null, global);
goog.exportSymbol('proto.PbModel.Team.TeamHeroItem', null, global);
goog.exportSymbol('proto.PbModel.Team.TeamPlanInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.Team.ModuleTeamInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.Team.ModuleTeamInfo.repeatedFields_, null);
};
goog.inherits(proto.PbModel.Team.ModuleTeamInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.Team.ModuleTeamInfo.displayName = 'proto.PbModel.Team.ModuleTeamInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.Team.Team = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.Team.Team.repeatedFields_, null);
};
goog.inherits(proto.PbModel.Team.Team, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.Team.Team.displayName = 'proto.PbModel.Team.Team';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.Team.TeamHeroItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.Team.TeamHeroItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.Team.TeamHeroItem.displayName = 'proto.PbModel.Team.TeamHeroItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.Team.TeamHeroDetailInfoItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.Team.TeamHeroDetailInfoItem.repeatedFields_, null);
};
goog.inherits(proto.PbModel.Team.TeamHeroDetailInfoItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.Team.TeamHeroDetailInfoItem.displayName = 'proto.PbModel.Team.TeamHeroDetailInfoItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.Team.TeamPlanInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.Team.TeamPlanInfo.repeatedFields_, null);
};
goog.inherits(proto.PbModel.Team.TeamPlanInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.Team.TeamPlanInfo.displayName = 'proto.PbModel.Team.TeamPlanInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.Team.ModuleTeamInfo.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.Team.ModuleTeamInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.Team.ModuleTeamInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.Team.ModuleTeamInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.ModuleTeamInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    submoduleid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    teaminfoList: jspb.Message.toObjectList(msg.getTeaminfoList(),
    proto.PbModel.Team.Team.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.Team.ModuleTeamInfo}
 */
proto.PbModel.Team.ModuleTeamInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.Team.ModuleTeamInfo;
  return proto.PbModel.Team.ModuleTeamInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.Team.ModuleTeamInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.Team.ModuleTeamInfo}
 */
proto.PbModel.Team.ModuleTeamInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSubmoduleid(value);
      break;
    case 2:
      var value = new proto.PbModel.Team.Team;
      reader.readMessage(value,proto.PbModel.Team.Team.deserializeBinaryFromReader);
      msg.addTeaminfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.Team.ModuleTeamInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.Team.ModuleTeamInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.Team.ModuleTeamInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.ModuleTeamInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSubmoduleid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTeaminfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.PbModel.Team.Team.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 SubModuleId = 1;
 * @return {number}
 */
proto.PbModel.Team.ModuleTeamInfo.prototype.getSubmoduleid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.ModuleTeamInfo} returns this
 */
proto.PbModel.Team.ModuleTeamInfo.prototype.setSubmoduleid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated Team TeamInfo = 2;
 * @return {!Array<!proto.PbModel.Team.Team>}
 */
proto.PbModel.Team.ModuleTeamInfo.prototype.getTeaminfoList = function() {
  return /** @type{!Array<!proto.PbModel.Team.Team>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.Team.Team, 2));
};


/**
 * @param {!Array<!proto.PbModel.Team.Team>} value
 * @return {!proto.PbModel.Team.ModuleTeamInfo} returns this
*/
proto.PbModel.Team.ModuleTeamInfo.prototype.setTeaminfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.PbModel.Team.Team=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.Team.Team}
 */
proto.PbModel.Team.ModuleTeamInfo.prototype.addTeaminfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.PbModel.Team.Team, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.Team.ModuleTeamInfo} returns this
 */
proto.PbModel.Team.ModuleTeamInfo.prototype.clearTeaminfoList = function() {
  return this.setTeaminfoList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.Team.Team.repeatedFields_ = [4,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.Team.Team.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.Team.Team.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.Team.Team} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.Team.toObject = function(includeInstance, msg) {
  var f, obj = {
    teamid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    fap: jspb.Message.getFieldWithDefault(msg, 2, 0),
    state: jspb.Message.getFieldWithDefault(msg, 3, 0),
    herolistList: jspb.Message.toObjectList(msg.getHerolistList(),
    proto.PbModel.Team.TeamHeroItem.toObject, includeInstance),
    releaseskillsmanual: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    herodetailinfolistList: jspb.Message.toObjectList(msg.getHerodetailinfolistList(),
    proto.PbModel.Team.TeamHeroDetailInfoItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.Team.Team}
 */
proto.PbModel.Team.Team.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.Team.Team;
  return proto.PbModel.Team.Team.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.Team.Team} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.Team.Team}
 */
proto.PbModel.Team.Team.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTeamid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFap(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setState(value);
      break;
    case 4:
      var value = new proto.PbModel.Team.TeamHeroItem;
      reader.readMessage(value,proto.PbModel.Team.TeamHeroItem.deserializeBinaryFromReader);
      msg.addHerolist(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReleaseskillsmanual(value);
      break;
    case 6:
      var value = new proto.PbModel.Team.TeamHeroDetailInfoItem;
      reader.readMessage(value,proto.PbModel.Team.TeamHeroDetailInfoItem.deserializeBinaryFromReader);
      msg.addHerodetailinfolist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.Team.Team.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.Team.Team.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.Team.Team} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.Team.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeamid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getFap();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getState();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getHerolistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.PbModel.Team.TeamHeroItem.serializeBinaryToWriter
    );
  }
  f = message.getReleaseskillsmanual();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getHerodetailinfolistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.PbModel.Team.TeamHeroDetailInfoItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 TeamId = 1;
 * @return {number}
 */
proto.PbModel.Team.Team.prototype.getTeamid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.Team} returns this
 */
proto.PbModel.Team.Team.prototype.setTeamid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 Fap = 2;
 * @return {number}
 */
proto.PbModel.Team.Team.prototype.getFap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.Team} returns this
 */
proto.PbModel.Team.Team.prototype.setFap = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 State = 3;
 * @return {number}
 */
proto.PbModel.Team.Team.prototype.getState = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.Team} returns this
 */
proto.PbModel.Team.Team.prototype.setState = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated TeamHeroItem HeroList = 4;
 * @return {!Array<!proto.PbModel.Team.TeamHeroItem>}
 */
proto.PbModel.Team.Team.prototype.getHerolistList = function() {
  return /** @type{!Array<!proto.PbModel.Team.TeamHeroItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.Team.TeamHeroItem, 4));
};


/**
 * @param {!Array<!proto.PbModel.Team.TeamHeroItem>} value
 * @return {!proto.PbModel.Team.Team} returns this
*/
proto.PbModel.Team.Team.prototype.setHerolistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.PbModel.Team.TeamHeroItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.Team.TeamHeroItem}
 */
proto.PbModel.Team.Team.prototype.addHerolist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.PbModel.Team.TeamHeroItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.Team.Team} returns this
 */
proto.PbModel.Team.Team.prototype.clearHerolistList = function() {
  return this.setHerolistList([]);
};


/**
 * optional bool ReleaseSkillsManual = 5;
 * @return {boolean}
 */
proto.PbModel.Team.Team.prototype.getReleaseskillsmanual = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.PbModel.Team.Team} returns this
 */
proto.PbModel.Team.Team.prototype.setReleaseskillsmanual = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * repeated TeamHeroDetailInfoItem HeroDetailInfoList = 6;
 * @return {!Array<!proto.PbModel.Team.TeamHeroDetailInfoItem>}
 */
proto.PbModel.Team.Team.prototype.getHerodetailinfolistList = function() {
  return /** @type{!Array<!proto.PbModel.Team.TeamHeroDetailInfoItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.Team.TeamHeroDetailInfoItem, 6));
};


/**
 * @param {!Array<!proto.PbModel.Team.TeamHeroDetailInfoItem>} value
 * @return {!proto.PbModel.Team.Team} returns this
*/
proto.PbModel.Team.Team.prototype.setHerodetailinfolistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.PbModel.Team.TeamHeroDetailInfoItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem}
 */
proto.PbModel.Team.Team.prototype.addHerodetailinfolist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.PbModel.Team.TeamHeroDetailInfoItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.Team.Team} returns this
 */
proto.PbModel.Team.Team.prototype.clearHerodetailinfolistList = function() {
  return this.setHerodetailinfolistList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.Team.TeamHeroItem.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.Team.TeamHeroItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.Team.TeamHeroItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.TeamHeroItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    heromodelid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    entityid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    location: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.Team.TeamHeroItem}
 */
proto.PbModel.Team.TeamHeroItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.Team.TeamHeroItem;
  return proto.PbModel.Team.TeamHeroItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.Team.TeamHeroItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.Team.TeamHeroItem}
 */
proto.PbModel.Team.TeamHeroItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeromodelid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntityid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLocation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.Team.TeamHeroItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.Team.TeamHeroItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.Team.TeamHeroItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.TeamHeroItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeromodelid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getEntityid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLocation();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 HeroModelId = 1;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroItem.prototype.getHeromodelid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroItem} returns this
 */
proto.PbModel.Team.TeamHeroItem.prototype.setHeromodelid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string EntityId = 2;
 * @return {string}
 */
proto.PbModel.Team.TeamHeroItem.prototype.getEntityid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.Team.TeamHeroItem} returns this
 */
proto.PbModel.Team.TeamHeroItem.prototype.setEntityid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 Location = 3;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroItem.prototype.getLocation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroItem} returns this
 */
proto.PbModel.Team.TeamHeroItem.prototype.setLocation = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.repeatedFields_ = [17];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.Team.TeamHeroDetailInfoItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.Team.TeamHeroDetailInfoItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    entityid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    heromodelid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ifnohero: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    name: jspb.Message.getFieldWithDefault(msg, 4, ""),
    fap: jspb.Message.getFieldWithDefault(msg, 5, 0),
    lv: jspb.Message.getFieldWithDefault(msg, 6, 0),
    star: jspb.Message.getFieldWithDefault(msg, 7, 0),
    starstage: jspb.Message.getFieldWithDefault(msg, 8, 0),
    fashionid: jspb.Message.getFieldWithDefault(msg, 9, 0),
    ifawakening: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    curhpper: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
    currentrp: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0),
    profession: jspb.Message.getFieldWithDefault(msg, 13, 0),
    ifothers: jspb.Message.getFieldWithDefault(msg, 14, 0),
    elitetype: jspb.Message.getFieldWithDefault(msg, 15, 0),
    totalattrMap: (f = msg.getTotalattrMap()) ? f.toObject(includeInstance, undefined) : [],
    skilllistList: (f = jspb.Message.getRepeatedField(msg, 17)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.Team.TeamHeroDetailInfoItem;
  return proto.PbModel.Team.TeamHeroDetailInfoItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.Team.TeamHeroDetailInfoItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntityid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeromodelid(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIfnohero(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFap(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLv(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStar(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStarstage(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFashionid(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIfawakening(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCurhpper(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCurrentrp(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProfession(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIfothers(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setElitetype(value);
      break;
    case 16:
      var value = msg.getTotalattrMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readInt64, null, 0, 0);
         });
      break;
    case 17:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setSkilllistList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.Team.TeamHeroDetailInfoItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.Team.TeamHeroDetailInfoItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntityid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHeromodelid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getIfnohero();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFap();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getLv();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getStar();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getStarstage();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getFashionid();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getIfawakening();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getCurhpper();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = message.getCurrentrp();
  if (f !== 0.0) {
    writer.writeDouble(
      12,
      f
    );
  }
  f = message.getProfession();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getIfothers();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getElitetype();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getTotalattrMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(16, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeInt64);
  }
  f = message.getSkilllistList();
  if (f.length > 0) {
    writer.writePackedInt32(
      17,
      f
    );
  }
};


/**
 * optional string EntityId = 1;
 * @return {string}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getEntityid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setEntityid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 HeroModelId = 2;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getHeromodelid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setHeromodelid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bool IfNoHero = 3;
 * @return {boolean}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getIfnohero = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setIfnohero = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string Name = 4;
 * @return {string}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 Fap = 5;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getFap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setFap = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 Lv = 6;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getLv = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setLv = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 Star = 7;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getStar = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setStar = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 StarStage = 8;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getStarstage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setStarstage = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 FashionId = 9;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getFashionid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setFashionid = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional bool IfAwakening = 10;
 * @return {boolean}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getIfawakening = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setIfawakening = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional double CurHpPer = 11;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getCurhpper = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setCurhpper = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional double CurrentRp = 12;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getCurrentrp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setCurrentrp = function(value) {
  return jspb.Message.setProto3FloatField(this, 12, value);
};


/**
 * optional int32 Profession = 13;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getProfession = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setProfession = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 IfOthers = 14;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getIfothers = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setIfothers = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 EliteType = 15;
 * @return {number}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getElitetype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setElitetype = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * map<int32, int64> TotalAttr = 16;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getTotalattrMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 16, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.clearTotalattrMap = function() {
  this.getTotalattrMap().clear();
  return this;};


/**
 * repeated int32 SkillList = 17;
 * @return {!Array<number>}
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.getSkilllistList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 17));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.setSkilllistList = function(value) {
  return jspb.Message.setField(this, 17, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.addSkilllist = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 17, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.Team.TeamHeroDetailInfoItem} returns this
 */
proto.PbModel.Team.TeamHeroDetailInfoItem.prototype.clearSkilllistList = function() {
  return this.setSkilllistList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.Team.TeamPlanInfo.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.Team.TeamPlanInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.Team.TeamPlanInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.Team.TeamPlanInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.TeamPlanInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    planid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    isdefault: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    teamlistList: jspb.Message.toObjectList(msg.getTeamlistList(),
    proto.PbModel.Team.Team.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.Team.TeamPlanInfo}
 */
proto.PbModel.Team.TeamPlanInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.Team.TeamPlanInfo;
  return proto.PbModel.Team.TeamPlanInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.Team.TeamPlanInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.Team.TeamPlanInfo}
 */
proto.PbModel.Team.TeamPlanInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlanid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsdefault(value);
      break;
    case 4:
      var value = new proto.PbModel.Team.Team;
      reader.readMessage(value,proto.PbModel.Team.Team.deserializeBinaryFromReader);
      msg.addTeamlist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.Team.TeamPlanInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.Team.TeamPlanInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.Team.TeamPlanInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.Team.TeamPlanInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlanid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIsdefault();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getTeamlistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.PbModel.Team.Team.serializeBinaryToWriter
    );
  }
};


/**
 * optional string PlanId = 1;
 * @return {string}
 */
proto.PbModel.Team.TeamPlanInfo.prototype.getPlanid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.Team.TeamPlanInfo} returns this
 */
proto.PbModel.Team.TeamPlanInfo.prototype.setPlanid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Name = 2;
 * @return {string}
 */
proto.PbModel.Team.TeamPlanInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.Team.TeamPlanInfo} returns this
 */
proto.PbModel.Team.TeamPlanInfo.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool IsDefault = 3;
 * @return {boolean}
 */
proto.PbModel.Team.TeamPlanInfo.prototype.getIsdefault = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.PbModel.Team.TeamPlanInfo} returns this
 */
proto.PbModel.Team.TeamPlanInfo.prototype.setIsdefault = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * repeated Team TeamList = 4;
 * @return {!Array<!proto.PbModel.Team.Team>}
 */
proto.PbModel.Team.TeamPlanInfo.prototype.getTeamlistList = function() {
  return /** @type{!Array<!proto.PbModel.Team.Team>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.Team.Team, 4));
};


/**
 * @param {!Array<!proto.PbModel.Team.Team>} value
 * @return {!proto.PbModel.Team.TeamPlanInfo} returns this
*/
proto.PbModel.Team.TeamPlanInfo.prototype.setTeamlistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.PbModel.Team.Team=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.Team.Team}
 */
proto.PbModel.Team.TeamPlanInfo.prototype.addTeamlist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.PbModel.Team.Team, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.Team.TeamPlanInfo} returns this
 */
proto.PbModel.Team.TeamPlanInfo.prototype.clearTeamlistList = function() {
  return this.setTeamlistList([]);
};


goog.object.extend(exports, proto.PbModel.Team);
