// source: WorldBoss/WorldBossGetRank.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var WorldBoss_WorldBossGetBoss_pb = require('../WorldBoss/WorldBossGetBoss_pb.js');
goog.object.extend(proto, WorldBoss_WorldBossGetBoss_pb);
goog.exportSymbol('proto.PbModel.WorldBoss.WorldBossGetRankReq', null, global);
goog.exportSymbol('proto.PbModel.WorldBoss.WorldBossGetRankRes', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.WorldBoss.WorldBossGetRankReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.WorldBoss.WorldBossGetRankReq.displayName = 'proto.PbModel.WorldBoss.WorldBossGetRankReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.WorldBoss.WorldBossGetRankRes.repeatedFields_, null);
};
goog.inherits(proto.PbModel.WorldBoss.WorldBossGetRankRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.WorldBoss.WorldBossGetRankRes.displayName = 'proto.PbModel.WorldBoss.WorldBossGetRankRes';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.WorldBoss.WorldBossGetRankReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.WorldBoss.WorldBossGetRankReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    bossid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankReq}
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.WorldBoss.WorldBossGetRankReq;
  return proto.PbModel.WorldBoss.WorldBossGetRankReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.WorldBoss.WorldBossGetRankReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankReq}
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBossid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.WorldBoss.WorldBossGetRankReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.WorldBoss.WorldBossGetRankReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBossid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 BossId = 1;
 * @return {number}
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq.prototype.getBossid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankReq} returns this
 */
proto.PbModel.WorldBoss.WorldBossGetRankReq.prototype.setBossid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.WorldBoss.WorldBossGetRankRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.WorldBoss.WorldBossGetRankRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerrankList: jspb.Message.toObjectList(msg.getPlayerrankList(),
    WorldBoss_WorldBossGetBoss_pb.PlayerRank.toObject, includeInstance),
    bossinfo: (f = msg.getBossinfo()) && WorldBoss_WorldBossGetBoss_pb.BossModel.toObject(includeInstance, f),
    playerdata: (f = msg.getPlayerdata()) && WorldBoss_WorldBossGetBoss_pb.PlayerData.toObject(includeInstance, f),
    myrank: jspb.Message.getFieldWithDefault(msg, 4, 0),
    selfdmg: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.WorldBoss.WorldBossGetRankRes;
  return proto.PbModel.WorldBoss.WorldBossGetRankRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.WorldBoss.WorldBossGetRankRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new WorldBoss_WorldBossGetBoss_pb.PlayerRank;
      reader.readMessage(value,WorldBoss_WorldBossGetBoss_pb.PlayerRank.deserializeBinaryFromReader);
      msg.addPlayerrank(value);
      break;
    case 2:
      var value = new WorldBoss_WorldBossGetBoss_pb.BossModel;
      reader.readMessage(value,WorldBoss_WorldBossGetBoss_pb.BossModel.deserializeBinaryFromReader);
      msg.setBossinfo(value);
      break;
    case 3:
      var value = new WorldBoss_WorldBossGetBoss_pb.PlayerData;
      reader.readMessage(value,WorldBoss_WorldBossGetBoss_pb.PlayerData.deserializeBinaryFromReader);
      msg.setPlayerdata(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMyrank(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSelfdmg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.WorldBoss.WorldBossGetRankRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.WorldBoss.WorldBossGetRankRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerrankList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      WorldBoss_WorldBossGetBoss_pb.PlayerRank.serializeBinaryToWriter
    );
  }
  f = message.getBossinfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      WorldBoss_WorldBossGetBoss_pb.BossModel.serializeBinaryToWriter
    );
  }
  f = message.getPlayerdata();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      WorldBoss_WorldBossGetBoss_pb.PlayerData.serializeBinaryToWriter
    );
  }
  f = message.getMyrank();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSelfdmg();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * repeated PlayerRank PlayerRank = 1;
 * @return {!Array<!proto.PbModel.WorldBoss.PlayerRank>}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.getPlayerrankList = function() {
  return /** @type{!Array<!proto.PbModel.WorldBoss.PlayerRank>} */ (
    jspb.Message.getRepeatedWrapperField(this, WorldBoss_WorldBossGetBoss_pb.PlayerRank, 1));
};


/**
 * @param {!Array<!proto.PbModel.WorldBoss.PlayerRank>} value
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes} returns this
*/
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.setPlayerrankList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.PbModel.WorldBoss.PlayerRank=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.WorldBoss.PlayerRank}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.addPlayerrank = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.PbModel.WorldBoss.PlayerRank, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes} returns this
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.clearPlayerrankList = function() {
  return this.setPlayerrankList([]);
};


/**
 * optional BossModel BossInfo = 2;
 * @return {?proto.PbModel.WorldBoss.BossModel}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.getBossinfo = function() {
  return /** @type{?proto.PbModel.WorldBoss.BossModel} */ (
    jspb.Message.getWrapperField(this, WorldBoss_WorldBossGetBoss_pb.BossModel, 2));
};


/**
 * @param {?proto.PbModel.WorldBoss.BossModel|undefined} value
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes} returns this
*/
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.setBossinfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes} returns this
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.clearBossinfo = function() {
  return this.setBossinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.hasBossinfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PlayerData PlayerData = 3;
 * @return {?proto.PbModel.WorldBoss.PlayerData}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.getPlayerdata = function() {
  return /** @type{?proto.PbModel.WorldBoss.PlayerData} */ (
    jspb.Message.getWrapperField(this, WorldBoss_WorldBossGetBoss_pb.PlayerData, 3));
};


/**
 * @param {?proto.PbModel.WorldBoss.PlayerData|undefined} value
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes} returns this
*/
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.setPlayerdata = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes} returns this
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.clearPlayerdata = function() {
  return this.setPlayerdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.hasPlayerdata = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 MyRank = 4;
 * @return {number}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.getMyrank = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes} returns this
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.setMyrank = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 SelfDmg = 5;
 * @return {number}
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.getSelfdmg = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.WorldBoss.WorldBossGetRankRes} returns this
 */
proto.PbModel.WorldBoss.WorldBossGetRankRes.prototype.setSelfdmg = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


goog.object.extend(exports, proto.PbModel.WorldBoss);
