// source: ActivityDepot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Resource_pb = require('./Resource_pb.js');
goog.object.extend(proto, Resource_pb);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotBuyReq', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotBuyRes', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotConfig', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotData', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotDrawReq', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotDrawRes', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig', null, global);
goog.exportSymbol('proto.PbModel.ActivityDepot.ActivityDepotRewardConfig', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotBuyReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotBuyReq.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotBuyReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotBuyRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotBuyRes.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotBuyRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotDrawReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotDrawReq.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotDrawReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotDrawRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotDrawRes.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotDrawRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotData.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.repeatedFields_, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.ActivityDepot.ActivityDepotConfig.repeatedFields_, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotConfig.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ActivityDepot.ActivityDepotRewardConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.displayName = 'proto.PbModel.ActivityDepot.ActivityDepotRewardConfig';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotBuyReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotBuyReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    activityid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    num: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotBuyReq}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotBuyReq;
  return proto.PbModel.ActivityDepot.ActivityDepotBuyReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotBuyReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotBuyReq}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setActivityid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotBuyReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotBuyReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivityid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNum();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 ActivityId = 1;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.prototype.getActivityid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotBuyReq} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.prototype.setActivityid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 Num = 2;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.prototype.getNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotBuyReq} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyReq.prototype.setNum = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotBuyRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotBuyRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    basegetgameresourcelist: (f = msg.getBasegetgameresourcelist()) && Resource_pb.ResourceToClientModel.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotBuyRes}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotBuyRes;
  return proto.PbModel.ActivityDepot.ActivityDepotBuyRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotBuyRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotBuyRes}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new Resource_pb.ResourceToClientModel;
      reader.readMessage(value,Resource_pb.ResourceToClientModel.deserializeBinaryFromReader);
      msg.setBasegetgameresourcelist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotBuyRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotBuyRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBasegetgameresourcelist();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      Resource_pb.ResourceToClientModel.serializeBinaryToWriter
    );
  }
};


/**
 * optional PbModel.Resource.ResourceToClientModel BaseGetGameResourceList = 2;
 * @return {?proto.PbModel.Resource.ResourceToClientModel}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.prototype.getBasegetgameresourcelist = function() {
  return /** @type{?proto.PbModel.Resource.ResourceToClientModel} */ (
    jspb.Message.getWrapperField(this, Resource_pb.ResourceToClientModel, 2));
};


/**
 * @param {?proto.PbModel.Resource.ResourceToClientModel|undefined} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotBuyRes} returns this
*/
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.prototype.setBasegetgameresourcelist = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotBuyRes} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.prototype.clearBasegetgameresourcelist = function() {
  return this.setBasegetgameresourcelist(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.ActivityDepot.ActivityDepotBuyRes.prototype.hasBasegetgameresourcelist = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    activityid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    drawid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    rewardid: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq;
  return proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setActivityid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDrawid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRewardid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivityid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getDrawid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getRewardid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 ActivityId = 1;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.prototype.getActivityid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.prototype.setActivityid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 DrawId = 2;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.prototype.getDrawid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.prototype.setDrawid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 RewardId = 3;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.prototype.getRewardid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardReq.prototype.setRewardid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    activitydepotdata: (f = msg.getActivitydepotdata()) && proto.PbModel.ActivityDepot.ActivityDepotData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes;
  return proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.PbModel.ActivityDepot.ActivityDepotData;
      reader.readMessage(value,proto.PbModel.ActivityDepot.ActivityDepotData.deserializeBinaryFromReader);
      msg.setActivitydepotdata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivitydepotdata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.PbModel.ActivityDepot.ActivityDepotData.serializeBinaryToWriter
    );
  }
};


/**
 * optional ActivityDepotData ActivityDepotData = 1;
 * @return {?proto.PbModel.ActivityDepot.ActivityDepotData}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.prototype.getActivitydepotdata = function() {
  return /** @type{?proto.PbModel.ActivityDepot.ActivityDepotData} */ (
    jspb.Message.getWrapperField(this, proto.PbModel.ActivityDepot.ActivityDepotData, 1));
};


/**
 * @param {?proto.PbModel.ActivityDepot.ActivityDepotData|undefined} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes} returns this
*/
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.prototype.setActivitydepotdata = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.prototype.clearActivitydepotdata = function() {
  return this.setActivitydepotdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.ActivityDepot.ActivityDepotChooseRewardRes.prototype.hasActivitydepotdata = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotDrawReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotDrawReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    activityid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawReq}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotDrawReq;
  return proto.PbModel.ActivityDepot.ActivityDepotDrawReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotDrawReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawReq}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setActivityid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotDrawReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotDrawReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivityid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 ActivityId = 1;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq.prototype.getActivityid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawReq} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawReq.prototype.setActivityid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotDrawRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    activitydepotdata: (f = msg.getActivitydepotdata()) && proto.PbModel.ActivityDepot.ActivityDepotData.toObject(includeInstance, f),
    basegetgameresourcelist: (f = msg.getBasegetgameresourcelist()) && Resource_pb.ResourceToClientModel.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotDrawRes;
  return proto.PbModel.ActivityDepot.ActivityDepotDrawRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.PbModel.ActivityDepot.ActivityDepotData;
      reader.readMessage(value,proto.PbModel.ActivityDepot.ActivityDepotData.deserializeBinaryFromReader);
      msg.setActivitydepotdata(value);
      break;
    case 3:
      var value = new Resource_pb.ResourceToClientModel;
      reader.readMessage(value,Resource_pb.ResourceToClientModel.deserializeBinaryFromReader);
      msg.setBasegetgameresourcelist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotDrawRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getActivitydepotdata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.PbModel.ActivityDepot.ActivityDepotData.serializeBinaryToWriter
    );
  }
  f = message.getBasegetgameresourcelist();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      Resource_pb.ResourceToClientModel.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional ActivityDepotData ActivityDepotData = 2;
 * @return {?proto.PbModel.ActivityDepot.ActivityDepotData}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.getActivitydepotdata = function() {
  return /** @type{?proto.PbModel.ActivityDepot.ActivityDepotData} */ (
    jspb.Message.getWrapperField(this, proto.PbModel.ActivityDepot.ActivityDepotData, 2));
};


/**
 * @param {?proto.PbModel.ActivityDepot.ActivityDepotData|undefined} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes} returns this
*/
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.setActivitydepotdata = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.clearActivitydepotdata = function() {
  return this.setActivitydepotdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.hasActivitydepotdata = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PbModel.Resource.ResourceToClientModel BaseGetGameResourceList = 3;
 * @return {?proto.PbModel.Resource.ResourceToClientModel}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.getBasegetgameresourcelist = function() {
  return /** @type{?proto.PbModel.Resource.ResourceToClientModel} */ (
    jspb.Message.getWrapperField(this, Resource_pb.ResourceToClientModel, 3));
};


/**
 * @param {?proto.PbModel.Resource.ResourceToClientModel|undefined} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes} returns this
*/
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.setBasegetgameresourcelist = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotDrawRes} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.clearBasegetgameresourcelist = function() {
  return this.setBasegetgameresourcelist(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.ActivityDepot.ActivityDepotDrawRes.prototype.hasBasegetgameresourcelist = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    activityid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq;
  return proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setActivityid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivityid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 ActivityId = 1;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.prototype.getActivityid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoReq.prototype.setActivityid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    activitydepotdata: (f = msg.getActivitydepotdata()) && proto.PbModel.ActivityDepot.ActivityDepotData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes;
  return proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.PbModel.ActivityDepot.ActivityDepotData;
      reader.readMessage(value,proto.PbModel.ActivityDepot.ActivityDepotData.deserializeBinaryFromReader);
      msg.setActivitydepotdata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivitydepotdata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.PbModel.ActivityDepot.ActivityDepotData.serializeBinaryToWriter
    );
  }
};


/**
 * optional ActivityDepotData ActivityDepotData = 1;
 * @return {?proto.PbModel.ActivityDepot.ActivityDepotData}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.prototype.getActivitydepotdata = function() {
  return /** @type{?proto.PbModel.ActivityDepot.ActivityDepotData} */ (
    jspb.Message.getWrapperField(this, proto.PbModel.ActivityDepot.ActivityDepotData, 1));
};


/**
 * @param {?proto.PbModel.ActivityDepot.ActivityDepotData|undefined} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes} returns this
*/
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.prototype.setActivitydepotdata = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.prototype.clearActivitydepotdata = function() {
  return this.setActivitydepotdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PbModel.ActivityDepot.ActivityDepotGetInfoRes.prototype.hasActivitydepotdata = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotData.toObject = function(includeInstance, msg) {
  var f, obj = {
    round: jspb.Message.getFieldWithDefault(msg, 1, 0),
    layer: jspb.Message.getFieldWithDefault(msg, 2, 0),
    maxround: jspb.Message.getFieldWithDefault(msg, 3, 0),
    reward: jspb.Message.getFieldWithDefault(msg, 4, ""),
    cost: jspb.Message.getFieldWithDefault(msg, 5, ""),
    drawconfiginfoMap: (f = msg.getDrawconfiginfoMap()) ? f.toObject(includeInstance, proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.toObject) : [],
    drawcost: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotData;
  return proto.PbModel.ActivityDepot.ActivityDepotData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRound(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLayer(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxround(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setReward(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCost(value);
      break;
    case 6:
      var value = msg.getDrawconfiginfoMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.deserializeBinaryFromReader, 0, new proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig());
         });
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDrawcost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRound();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getLayer();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMaxround();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getReward();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCost();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDrawconfiginfoMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.serializeBinaryToWriter);
  }
  f = message.getDrawcost();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional int32 Round = 1;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.getRound = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.setRound = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 Layer = 2;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.getLayer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.setLayer = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 MaxRound = 3;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.getMaxround = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.setMaxround = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string Reward = 4;
 * @return {string}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.getReward = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.setReward = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string Cost = 5;
 * @return {string}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.getCost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.setCost = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * map<int32, ActivityDepotListActivityDepotConfig> DrawConfigInfo = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig>}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.getDrawconfiginfoMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.clearDrawconfiginfoMap = function() {
  this.getDrawconfiginfoMap().clear();
  return this;};


/**
 * optional string DrawCost = 7;
 * @return {string}
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.getDrawcost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotData} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotData.prototype.setDrawcost = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    activitydepotconfigsList: jspb.Message.toObjectList(msg.getActivitydepotconfigsList(),
    proto.PbModel.ActivityDepot.ActivityDepotConfig.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig}
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig;
  return proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig}
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.PbModel.ActivityDepot.ActivityDepotConfig;
      reader.readMessage(value,proto.PbModel.ActivityDepot.ActivityDepotConfig.deserializeBinaryFromReader);
      msg.addActivitydepotconfigs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActivitydepotconfigsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.PbModel.ActivityDepot.ActivityDepotConfig.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ActivityDepotConfig ActivityDepotConfigs = 1;
 * @return {!Array<!proto.PbModel.ActivityDepot.ActivityDepotConfig>}
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.prototype.getActivitydepotconfigsList = function() {
  return /** @type{!Array<!proto.PbModel.ActivityDepot.ActivityDepotConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.ActivityDepot.ActivityDepotConfig, 1));
};


/**
 * @param {!Array<!proto.PbModel.ActivityDepot.ActivityDepotConfig>} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig} returns this
*/
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.prototype.setActivitydepotconfigsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig}
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.prototype.addActivitydepotconfigs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.PbModel.ActivityDepot.ActivityDepotConfig, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotListActivityDepotConfig.prototype.clearActivitydepotconfigsList = function() {
  return this.setActivitydepotconfigsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    slot: jspb.Message.getFieldWithDefault(msg, 2, 0),
    reward: jspb.Message.getFieldWithDefault(msg, 3, ""),
    rewardpoolid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    uplayernum: jspb.Message.getFieldWithDefault(msg, 5, 0),
    chooserewardid: jspb.Message.getFieldWithDefault(msg, 6, 0),
    rewardpoolList: jspb.Message.toObjectList(msg.getRewardpoolList(),
    proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.toObject, includeInstance),
    isfinish: jspb.Message.getBooleanFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotConfig;
  return proto.PbModel.ActivityDepot.ActivityDepotConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSlot(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setReward(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRewardpoolid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUplayernum(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChooserewardid(value);
      break;
    case 7:
      var value = new proto.PbModel.ActivityDepot.ActivityDepotRewardConfig;
      reader.readMessage(value,proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.deserializeBinaryFromReader);
      msg.addRewardpool(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsfinish(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSlot();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getReward();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRewardpoolid();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getUplayernum();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getChooserewardid();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getRewardpoolList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.serializeBinaryToWriter
    );
  }
  f = message.getIsfinish();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 Slot = 2;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.getSlot = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.setSlot = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string Reward = 3;
 * @return {string}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.getReward = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.setReward = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 RewardPoolId = 4;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.getRewardpoolid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.setRewardpoolid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 UpLayerNum = 5;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.getUplayernum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.setUplayernum = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 ChooseRewardId = 6;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.getChooserewardid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.setChooserewardid = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated ActivityDepotRewardConfig RewardPool = 7;
 * @return {!Array<!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig>}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.getRewardpoolList = function() {
  return /** @type{!Array<!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.ActivityDepot.ActivityDepotRewardConfig, 7));
};


/**
 * @param {!Array<!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig>} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
*/
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.setRewardpoolList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.addRewardpool = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.PbModel.ActivityDepot.ActivityDepotRewardConfig, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.clearRewardpoolList = function() {
  return this.setRewardpoolList([]);
};


/**
 * optional bool IsFinish = 8;
 * @return {boolean}
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.getIsfinish = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotConfig.prototype.setIsfinish = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    reward: jspb.Message.getFieldWithDefault(msg, 2, ""),
    openround: jspb.Message.getFieldWithDefault(msg, 3, 0),
    num: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig}
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ActivityDepot.ActivityDepotRewardConfig;
  return proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig}
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReward(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOpenround(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getReward();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOpenround();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getNum();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string Reward = 2;
 * @return {string}
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.getReward = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.setReward = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 OpenRound = 3;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.getOpenround = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.setOpenround = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 Num = 4;
 * @return {number}
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.getNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ActivityDepot.ActivityDepotRewardConfig} returns this
 */
proto.PbModel.ActivityDepot.ActivityDepotRewardConfig.prototype.setNum = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


goog.object.extend(exports, proto.PbModel.ActivityDepot);
