// source: ZhanQu.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes', null, global);
goog.exportSymbol('proto.PbModel.ZhanQu.ZhanQuZoneInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.repeatedFields_, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.repeatedFields_, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneInfo.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.repeatedFields_, null);
};
goog.inherits(proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.displayName = 'proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    mainzoneid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    subzoneid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq;
  return proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMainzoneid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubzoneid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMainzoneid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSubzoneid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string MainZoneId = 1;
 * @return {string}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.prototype.getMainzoneid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.prototype.setMainzoneid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string SubZoneId = 2;
 * @return {string}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.prototype.getSubzoneid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeReq.prototype.setSubzoneid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes;
  return proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneCustomMergeRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    servergroupid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq;
  return proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setServergroupid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServergroupid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 ServerGroupId = 1;
 * @return {number}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.prototype.getServergroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdReq.prototype.setServergroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    servergroupidsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes;
  return proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setServergroupidsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServergroupidsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      1,
      f
    );
  }
};


/**
 * repeated int32 ServerGroupIds = 1;
 * @return {!Array<number>}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.prototype.getServergroupidsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.prototype.setServergroupidsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.prototype.addServergroupids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetSubServerGroupIdRes.prototype.clearServergroupidsList = function() {
  return this.setServergroupidsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    servergroupid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq;
  return proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setServergroupid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServergroupid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 ServerGroupId = 1;
 * @return {number}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.prototype.getServergroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdReq.prototype.setServergroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    zoneid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes;
  return proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setZoneid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getZoneid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string ZoneId = 1;
 * @return {string}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.prototype.getZoneid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneIdRes.prototype.setZoneid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq;
  return proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    infosList: jspb.Message.toObjectList(msg.getInfosList(),
    proto.PbModel.ZhanQu.ZhanQuZoneInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes;
  return proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.PbModel.ZhanQu.ZhanQuZoneInfo;
      reader.readMessage(value,proto.PbModel.ZhanQu.ZhanQuZoneInfo.deserializeBinaryFromReader);
      msg.addInfos(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.PbModel.ZhanQu.ZhanQuZoneInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ZhanQuZoneInfo Infos = 1;
 * @return {!Array<!proto.PbModel.ZhanQu.ZhanQuZoneInfo>}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.prototype.getInfosList = function() {
  return /** @type{!Array<!proto.PbModel.ZhanQu.ZhanQuZoneInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PbModel.ZhanQu.ZhanQuZoneInfo, 1));
};


/**
 * @param {!Array<!proto.PbModel.ZhanQu.ZhanQuZoneInfo>} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes} returns this
*/
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.prototype.setInfosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneInfo}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.prototype.addInfos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.PbModel.ZhanQu.ZhanQuZoneInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetZoneInfosRes.prototype.clearInfosList = function() {
  return this.setInfosList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    zoneid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    targetgroupid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    step: jspb.Message.getFieldWithDefault(msg, 3, 0),
    mingroupid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    maxgroupid: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneInfo}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneInfo;
  return proto.PbModel.ZhanQu.ZhanQuZoneInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneInfo}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setZoneid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTargetgroupid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStep(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMingroupid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxgroupid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getZoneid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTargetgroupid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getStep();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getMingroupid();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getMaxgroupid();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional string ZoneId = 1;
 * @return {string}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.getZoneid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneInfo} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.setZoneid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 TargetGroupId = 2;
 * @return {number}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.getTargetgroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneInfo} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.setTargetgroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 Step = 3;
 * @return {number}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.getStep = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneInfo} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.setStep = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 MinGroupId = 4;
 * @return {number}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.getMingroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneInfo} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.setMingroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 MaxGroupId = 5;
 * @return {number}
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.getMaxgroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneInfo} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneInfo.prototype.setMaxgroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    servergroupid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq;
  return proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setServergroupid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServergroupid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 ServerGroupId = 1;
 * @return {number}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.prototype.getServergroupid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoReq.prototype.setServergroupid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.toObject = function(opt_includeInstance) {
  return proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    selfzoneid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nearzoneid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    mergetimetick: jspb.Message.getFieldWithDefault(msg, 3, 0),
    selfzhanquservergroupidsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    nearzhanquservergroupidsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes;
  return proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSelfzoneid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNearzoneid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMergetimetick(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setSelfzhanquservergroupidsList(value);
      break;
    case 5:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setNearzhanquservergroupidsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSelfzoneid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNearzoneid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMergetimetick();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getSelfzhanquservergroupidsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      4,
      f
    );
  }
  f = message.getNearzhanquservergroupidsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      5,
      f
    );
  }
};


/**
 * optional string SelfZoneId = 1;
 * @return {string}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.getSelfzoneid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.setSelfzoneid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string NearZoneId = 2;
 * @return {string}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.getNearzoneid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.setNearzoneid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 MergeTimeTick = 3;
 * @return {number}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.getMergetimetick = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.setMergetimetick = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated int32 SelfZhanquServerGroupIds = 4;
 * @return {!Array<number>}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.getSelfzhanquservergroupidsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.setSelfzhanquservergroupidsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.addSelfzhanquservergroupids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.clearSelfzhanquservergroupidsList = function() {
  return this.setSelfzhanquservergroupidsList([]);
};


/**
 * repeated int32 NearZhanquServerGroupIds = 5;
 * @return {!Array<number>}
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.getNearzhanquservergroupidsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.setNearzhanquservergroupidsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.addNearzhanquservergroupids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes} returns this
 */
proto.PbModel.ZhanQu.ZhanQuZoneGetMergeInfoRes.prototype.clearNearzhanquservergroupidsList = function() {
  return this.setNearzhanquservergroupidsList([]);
};


goog.object.extend(exports, proto.PbModel.ZhanQu);
